### PR TITLE
NodeJS wrapper for Wasabi

### PR DESCRIPTION
**Pull request by yabeow**
Hi Daniel,

I just have implemented a NodeJS wrapper for Wasabi. It will be useful if we could use Wasabi from NodeJS to support automatic integration tests for analyses with some libraries like [puppeteer](https://github.com/GoogleChrome/puppeteer).

It's the first time I have written in Rust language so welcome for any feedback. Hope it will be merged soon.

P/s: This actually a part of my research project in university. I'm working on with your guy's awesome paper :+1:

### CODE REVIEW

**Comment by danleh** [comment]
Hi there! Thanks, that's a very cool improvement :) I will have to take a look a bit later, but thanks for the PR already.

**Comment by yabeow** [comment]
Hi @danleh ,
It has been several months now :)
Please take a look at it.

**Comment by danleh** [comment]
That's right, sorry for the delay.

Unfortunately, I will not merge this PR at this time. The reasons are:
- Since I don't use Wasabi on Node.js myself, I cannot properly maintain the additions (and I don't have time to test it at the moment)
- I don't know neon and don't understand the nodejs wrapper code and I am hesitant to add code that I don't understand.
- From what I understood from a short glance: neon wraps the Wasabi binary to make it available in Node.js. I think a (long term) more streamlined way of using Wasabi in Node.js would be by compiling Wasabi itself to WebAssembly and execute that in Node.js. Then users don't have to install Rust and the dependencies etc.

I am not closing this though, since
- I want to reconsider, once I use Wasabi in Node.js myself
- still useful for other people

**Comment by danleh** [comment]
Wasabi now has a --nodejs option that should allow you to instrument Node.js JavaScript files (with require etc.). Its not well tested or documented, but since it exists, I close this for now.

**Pull request closed without merging**
